# Generated by Django 3.2.9 on 2021-12-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.IntegerField(verbose_name='Agência')),
                ('account_number', models.IntegerField(verbose_name='Número da Conta')),
                ('account_type', models.CharField(choices=[('001', 'Corrente'), ('013', 'Poupança')], max_length=8, verbose_name='Tipo da Conta')),
                ('balance', models.IntegerField(verbose_name='Saldo')),
            ],
        ),
    ]
