# Generated by Django 3.2.9 on 2021-12-03 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20211202_2130'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='id_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conta',
            name='account_number',
            field=models.CharField(max_length=7, verbose_name='Número da Conta'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='agency',
            field=models.CharField(max_length=10, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='balance',
            field=models.FloatField(verbose_name='Saldo'),
        ),
        migrations.AlterModelTable(
            name='conta',
            table='bank_account',
        ),
    ]
