# Generated by Django 3.2.9 on 2021-12-02 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PIX', 'PIX'), ('TED', 'TED'), ('DOC', 'DOC')], max_length=3, verbose_name='Tipo de Transferência')),
                ('amount', models.IntegerField(verbose_name='Saldo')),
                ('date_time', models.DateTimeField(verbose_name='Data e Horário')),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contas.conta')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contas.conta')),
            ],
        ),
    ]
