# Generated by Django 3.2.9 on 2021-12-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0002_auto_20211202_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferencia',
            old_name='id_recipient',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='transferencia',
            old_name='id_sender',
            new_name='sender',
        ),
    ]
