# Generated by Django 3.2.9 on 2021-12-02 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_alter_endereco_number'),
        ('contas', '0001_initial'),
        ('clientes', '0004_auto_20211201_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contas.conta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enderecos.endereco'),
            preserve_default=False,
        ),
    ]
