# Generated by Django 3.2.9 on 2021-12-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20211202_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='account',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='address',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='given_name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefone'),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='client',
        ),
    ]
