# Generated by Django 3.2.9 on 2021-12-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='number',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
