# Generated by Django 3.2.9 on 2021-12-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_alter_endereco_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='number',
        ),
        migrations.AddField(
            model_name='endereco',
            name='address_complement',
            field=models.CharField(default=1, max_length=100, verbose_name='Complemento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='building_number',
            field=models.CharField(default=1, max_length=5, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='district',
            field=models.CharField(max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Rua'),
        ),
        migrations.AlterModelTable(
            name='endereco',
            table='addresses',
        ),
    ]
