# Generated by Django 3.2.9 on 2021-12-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_auto_20211202_2130'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='endereco',
            table='address',
        ),
    ]
